{% set name = "python-gitlab" %}
{% set version = "4.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f4bc9e3267d255b18038c4bcdecce95c2ca792fc5654e1f6fbfd16962b73449c

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gitlab = gitlab.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2.22.0
    - requests-toolbelt >=0.9.1

test:
  imports:
    - gitlab

about:
  home: https://github.com/python-gitlab/python-gitlab
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING
  summary: Python wrapper for the GitLab API
  description: |
    python-gitlab is a Python package providing access to the GitLab
    server API. It supports the v4 API of GitLab, and provides a CLI
    tool (gitlab).
  doc_url: https://python-gitlab.readthedocs.io/
  dev_url: https://github.com/python-gitlab/python-gitlab

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
