{% set name = "python-gitlab" %}
{% set version = "6.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3d7764956948949a2a3aff2078e6e93a5efea2db0a29566b5e142091bcc075aa

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gitlab = gitlab.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.22.0
    - requests-toolbelt >=0.9.1
    - gql

test:
  requires:
    - python {{ python_min }}
  imports:
    - gitlab

about:
  home: https://github.com/python-gitlab/python-gitlab
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING
  summary: Python wrapper for the GitLab API
  description: |
    python-gitlab is a Python package providing access to the GitLab
    server API. It supports the v4 API of GitLab, and provides a CLI
    tool (gitlab).
  doc_url: https://python-gitlab.readthedocs.io/
  dev_url: https://github.com/python-gitlab/python-gitlab

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
